/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Podder
 */
public class NewJFrame4 extends javax.swing.JFrame {

    //String s1 = new String();
    PreparedStatement ps = null;
    ResultSet rs = null;
    public Connection conn = null;
    private Object Connect;

    /**
     * Creates new form NewJFrame4
     */
    public NewJFrame4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        department = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        back3 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        user.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("Username:");
        getContentPane().add(user);
        user.setBounds(86, 13, 122, 33);

        jTextField1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(212, 11, 158, 38);

        pass.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setText("Password:");
        getContentPane().add(pass);
        pass.setBounds(86, 60, 122, 33);

        name.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Name:");
        getContentPane().add(name);
        name.setBounds(86, 120, 122, 33);

        department.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        department.setForeground(new java.awt.Color(255, 255, 255));
        department.setText("Department:");
        getContentPane().add(department);
        department.setBounds(86, 176, 122, 33);

        jTextField3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(212, 118, 158, 38);

        jTextField4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(212, 174, 158, 38);

        jTextField6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(212, 230, 158, 38);

        age.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setText("Age:");
        getContentPane().add(age);
        age.setBounds(86, 232, 122, 33);

        sex.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        sex.setForeground(new java.awt.Color(255, 255, 255));
        sex.setText("Gender:");
        getContentPane().add(sex);
        sex.setBounds(86, 288, 122, 33);

        jTextField7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(jTextField7);
        jTextField7.setBounds(212, 286, 158, 38);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 398, 110, 52);

        back3.setBackground(new java.awt.Color(255, 0, 0));
        back3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        back3.setText("Back");
        back3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back3ActionPerformed(evt);
            }
        });
        getContentPane().add(back3);
        back3.setBounds(86, 400, 86, 52);

        jTextField8.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(jTextField8);
        jTextField8.setBounds(212, 342, 158, 38);

        id.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("ID:");
        getContentPane().add(id);
        id.setBounds(86, 344, 122, 33);

        jPasswordField1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(212, 60, 158, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, 0, 490, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Search
        ResultSet rs = null;
        PreparedStatement ps = null;
        String s = new String();
        String n = jTextField8.getText();
        String p = new String();
        //Search 
        s = "select * from st_table where id='" + n + "'";

        try {
            if (jTextField8.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "please enter id", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            ps = conn.prepareStatement(s);
            rs = ps.executeQuery();
            while (rs.next()) {
                JOptionPane.showMessageDialog(this, "Search succesfull");
                jTextField3.setText(rs.getString("name"));
                jTextField4.setText(rs.getString("department"));
                jTextField1.setText(rs.getString("username"));
                jPasswordField1.setText(rs.getString("password"));
                jTextField6.setText(rs.getString("age"));
                jTextField7.setText(rs.getString("sex"));
                //jTextField8.setText(rs.getString("id"));

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Not searching");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void back3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back3ActionPerformed
        // TODO add your handling code here:
        NewJFrame n = new NewJFrame();
        n.setVisible(true);
        dispose();

    }//GEN-LAST:event_back3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conn = Sqlite.ConnectDB();
    }//GEN-LAST:event_formWindowOpened

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JButton back3;
    private javax.swing.JLabel department;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel sex;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
